### ISSUE TITLE
Profile page: Incorrect listings

### ISSUE THREAD

**Issue by ilijabojanovic** [WeAreNewt/NonFungibleTime#257] opened 2022-02-22 12:00 UTC
Reproduction steps:
1. Go to https://elated-kalam-a67780.netlify.app/
2. Create some nfts
3. Buy some nfts
4. Go to profile page

Actual:
We display created nfts on both tabs. Created nfts are also listed on collected tab

Video:
https://www.screencast.com/t/fw4cuYNlyUKj

**Comment by donosonaumczuk** [comment] 2022-02-23 15:53
I will close this as it was intended that collected shows the ones you created but not sold

**Closed by donosonaumczuk** 2022-02-23 15:53 UTC
Labels: bug, high priority
